backend:
  name: github
  repo: Boxiaoli-Lab/zm-team
  branch: main
  base_url: https://sveltia-cms-auth.liboxiao19890504.workers.dev # 指向您在 Cloudflare 上的认证服务
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "collaborations"
    label: "科研合作项目"
    folder: "content/collaborations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "项目名称", name: "title", widget: "string"}
      - label: "合作团队成员"
        name: "members"
        widget: "select"
        multiple: true
        options:
          - "陈玉伟"
          - "段咏欣"
          - "张晓方"
          - "张晓方"
          - "张晓方"
          - "张晓方"
          - "张晓方"
          - "李柏霄"
          - "李明杰"
          
         
         
