backend:
  name: github
  repo: Boxiaoli-Lab/zm-team
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "collaborations"
    label: "科研合作项目"
    folder: "content/collaborations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "项目名称", name: "title", widget: "string"}
      - label: "合作团队成员"
        name: "members"
        widget: "select"
        multiple: true
        options:
          - "陈玉伟"
          - "张晓方"
          - "薛敏"
          - "李柏霄"
          - "李明杰"
          - "刘云青"
          - "孙依晓"
          - "王翔"
