backend:
  name: github
  repo: Boxiaoli-Lab/zm-team
  branch: main
  base_url: https://sveltia-cms-auth.liboxiao19890504.workers.dev
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "collaborations"
    label: "科研合作项目"
    folder: "content/collaborations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "项目名称", name: "title", widget: "string"}
      - label: "合作团队成员"
        name: "members"
        widget: "select"
        multiple: true
        options:
          - "陈玉伟"
          - "段咏欣"
          - "蒋敏"
          - "李柏霄"
          - "李明杰"
          - "刘云霄"
          - "孙依晗"
          - "王纲"
          - "王杰"
          - "王淑雪"
          - "乌皓"
          - "杨洪生"
          - "袁媛"
          - "张建明"
          - "张晓方"
          - "张泽军"
          - "周立娟"
          - "周丽娟"
          - "宗鲁"
